### ISSUE TITLE
DictNotFoundError: Dictionary for language 'en_US' could not be found

### ISSUE THREAD

**Issue by DevoAman** [susilnem/American-sign-Language#1]
hi,
i have installed all the requirements and also installed pyenchant but it shows this error could you help

**Comment by susilnem** [comment]
Did you try [Final Project / Source Code /Requirement.txt] (https://github.com/susilnem/American-sign-Language/blob/7bc613366aad0c8c8de34fbb10a6b2922fd0085f/Final%20Project/Source%20Code/requirement.txt) ?

**Comment by susilnem** [comment]
[Requirement](https://github.com/susilnem/American-sign-Language/blob/7bc613366aad0c8c8de34fbb10a6b2922fd0085f/Final%20Project/Source%20Code/requirement.txt)

**Comment by DevoAman** [comment]
yes, but it doesn't work.

if you don't mind can we connect with any disk

**Comment by susilnem** [comment]
Can you please try again? Cause its working fine or You can add Screensorts. @DevoAman

**Comment by DevoAman** [comment]
![Screenshot (25)](https://github.com/susilnem/American-sign-Language/assets/109810224/e9b2fa52-81c8-4d64-9cc7-8059c1b2c0f3)

Here is the screenshot of the errors
I have installed and imported enchant

Traceback (most recent call last):
  File "D:\American-sign-Language1\American-sign-Language-main\Final Project\Source Code\final_pred.py", line 15, in <module>
    ddd = enchant.Dict("en_US")
  File "C:\Users\Amanullah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 542, in __init__
    super().__init__()
  File "C:\Users\Amanullah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 144, in __init__
    self._init_this()
  File "C:\Users\Amanullah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "C:\Users\Amanullah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)
  File "C:\Users\Amanullah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 233, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
Please check https://pyenchant.github.io/pyenchant/ for details

**Comment by susilnem** [comment]
Firstof all, You need to install packages in an environment as mentioned rather than running globally. Please Follow this Procedure [Virtualenv](https://www.educative.io/answers/how-to-activate-virtualenv-windows)

**Comment by DevoAman** [comment]
sorry @susilnem it doesn't work 
I have created it by your preference and followed all the steps but it shows error
![Screenshot (26)](https://github.com/susilnem/American-sign-Language/assets/109810224/70fb4518-9ca3-4751-9da4-cda445f5786d)
![Screenshot (28)](https://github.com/susilnem/American-sign-Language/assets/109810224/9af0cc29-6719-4502-bb1a-6f8df8691b9b)
![Screenshot (29)](https://github.com/susilnem/American-sign-Language/assets/109810224/676fa384-1023-4f05-af3b-065f78e235cd)

**Comment by DevoAman** [comment]
If there is any other steps to be follow?
please give sone detail explaination.
![Screenshot (30)](https://github.com/susilnem/American-sign-Language/assets/109810224/741e62b1-0736-42a5-8f58-60693b9ae18b)

**Comment by DevoAman** [comment]
i don't know what i am missing .It is urgent kindly help me

**Comment by susilnem** [comment]
@DevoAman  Message me at susiltiwari750@gmail.com
